name: Run Benchmarks All

on:
  workflow_dispatch:
    inputs:
      runTimes:
        description: 'Test run times'
        required: true
        default: 1
        type: choice
        options:
        - 1
        - 5
        - 10
        - 100
      warmupTimes:
        description: 'Warmup times'
        required: true
        default: 1
        type: choice
        options:
        - 0
        - 1
        - 3

jobs:
  benchmark:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Collect Workflow Telemetry
        uses: konpeki622/workflow-telemetry-action@v1.0.5
      
      - name: Install
        run: |
          # Install dependencies
          npm install pnpm -g
          pnpm install --no-frozen-lockfile

          # Install hyperfine
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.17.0/hyperfine_1.17.0_amd64.deb
          sudo dpkg -i hyperfine_1.17.0_amd64.deb
      - name: Prepare test
        run: |
          node ./testCaseFactory/createCase.js 10000

      - name: Run tapjs
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:tapjs'
      - name: Run jasmine
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:jasmine'
      - name: Run jest
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:jest'
      - name: Run jest better
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:jest-better'
      - name: Run vitest
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:vitest'
      - name: Run vitest better
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:vitest-better'
      - name: Run vitest without isolation
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:vitest-no-isolate'
      - name: Run mocha
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:mocha'
      - name: Run mocha better
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:mocha-better'
      - name: Run qunit
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:qunit'
      - name: Run ava
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:ava'
      - name: Run jest:inline
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:jest:inline'
      - name: Run vitest:inline
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} 'pnpm run test:vitest:inline'
