name: Run Benchmarks Matrix

on:
  workflow_dispatch:
    inputs:
      runTimes:
        description: 'Number of times each framework test script runs'
        required: true
        default: 1
        type: choice
        options:
        - 2
        - 5
        - 10
        - 100
      warmupTimes:
        description: 'Warmup times'
        required: true
        default: 1
        type: choice
        options:
        - 0
        - 1
        - 3
      fileCount:
        description: 'Number of test files, Must be a multiple of 10'
        required: true
        default: 100
      caseCountInFile:
        description: 'Number of test cases in each test file, , Must be a multiple of 5'
        required: true
        default: 10
      cpuSpendMillisecond:
        description: 'CPU consumption per testcase(ms)'
        required: true
        default: 100
      ioSpendMillisecond:
        description: 'IO consumption per testcase(ms)'
        required: true
        default: 100
jobs:
  benchmark:
    strategy:
      matrix:
        test: ["'pnpm run test:jasmine'", 
        "'pnpm run test:jasmine-better'", 
        "'pnpm run test:jest'", 
        "'pnpm run test:jest-better'", 
        "'pnpm run test:jest-inline'", 
        "'pnpm run test:vitest'", 
        "'pnpm run test:vitest-better'", 
        "'pnpm run test:vitest-inline'", 
        "'pnpm run test:vitest-no-isolate'", 
        "'pnpm run test:mocha'", 
        "'pnpm run test:mocha-better'", 
        "'pnpm run test:qunit'", 
        "'pnpm run test:ava'", 
        "'pnpm run test:ava-inline'", 
        "'pnpm run test:tape'", 
        "'pnpm run test:tapjs'", 
        "'pnpm run test:tapjs-better'", 
        "'pnpm run test:tapjs-inline'", 
        "'pnpm run test:uvu'"]
        os: [ubuntu-latest]
    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Collect Workflow Telemetry
        uses: konpeki622/workflow-telemetry-action@v1.0.15
      
      - name: Install
        run: |
          # Install dependencies
          npm install pnpm -g
          pnpm install --no-frozen-lockfile

          # Install hyperfine
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.17.0/hyperfine_1.17.0_amd64.deb
          sudo dpkg -i hyperfine_1.17.0_amd64.deb

      - name: Prepare test
        run: |
          node ./testCaseFactory/createCase.js ${{ inputs.fileCount }} ${{ inputs.caseCountInFile }} ${{ inputs.cpuSpendMillisecond }} ${{ inputs.ioSpendMillisecond }}

      - name: Run test
        run: |
          hyperfine --warmup ${{ inputs.warmupTimes }} --runs ${{ inputs.runTimes }} ${{ matrix.test }}
