name: Run Test
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  benchmark-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Collect Workflow Telemetry
        uses: konpeki622/workflow-telemetry-action@v1.0.12
      
      - name: Install
        run: |
          # Install dependencies
          npm install pnpm -g
          pnpm install

          # Install hyperfine
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.17.0/hyperfine_1.17.0_amd64.deb
          sudo dpkg -i hyperfine_1.17.0_amd64.deb

      - name: Run test
        run: |
          pnpm run test:ben-linux
     
  benchmark-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Collect Workflow Telemetry
        uses: konpeki622/workflow-telemetry-action@v1.0.12
      
      - name: Install
        run: |
          # Install dependencies
          npm install pnpm -g
          pnpm install

      - name: Run test
        run: |
          pnpm run test:ben-windows
